# Skaffold handles the workflow for building and deploying kubernetes resources.
# see https://skaffold.dev/docs/references/yaml for more details.
#
apiVersion: skaffold/v2beta1
kind: Config
build: {}
deploy:
  kubectl:
    manifests:
    - .staroid/k8s/strapi.yaml
  statusCheckDeadlineSeconds: 360
profiles:
  - name: minikube
    patches:
      - op: add
        path: /deploy/kubectl/manifests/0
        value: .staroid/k8s/minikube.yaml
